In [1]:
from star_analysis.service.statistics_service import StatisticsService


service = StatisticsService()

[INFO][2023-06-11 20:56:18,762] image_downloader.py:download_exact:49: Downloading 8162 6 0080
[INFO][2023-06-11 20:56:39,701] image_downloader.py:download:34: Downloading 1000


In [2]:
service.get_channel_mean_variance(calculate=True)

  0%|          | 0/1050 [00:00<?, ?it/s]

(array([0.06806371, 0.20728613, 0.464     , 0.01954113, 0.393049  ],
       dtype=float32),
 array([1.3366362 , 2.3025422 , 1.7791781 , 0.80536276, 6.722137  ],
       dtype=float32))

In [2]:
service.get_number_examples_per_class(calculate=True)

  0%|          | 0/6 [00:00<?, ?it/s]

  0%|          | 0/6 [00:00<?, ?it/s]

array([ 155788., 1019846.])

In [3]:
service.get_color_covariance(calculate=True)

  0%|          | 0/1050 [00:00<?, ?it/s]

array([[38.39584431,  2.17935757,  0.98275128,  0.98868845,  2.09980341],
       [ 2.17935757, 81.56378697,  2.21487135,  0.94742019,  0.95599492],
       [ 0.98275128,  2.21487135, 29.7828834 ,  2.01658154,  0.88864766],
       [ 0.98868845,  0.94742019,  2.01658154, 52.01123953,  2.00083838],
       [ 2.09980341,  0.95599492,  0.88864766,  2.00083838, 26.48450165]])

In [6]:
import numpy as np
a = np.array([[38.39584431,  2.17935757,  0.98275128,  0.98868845,  2.09980341],
       [ 2.17935757, 81.56378697,  2.21487135,  0.94742019,  0.95599492],
       [ 0.98275128,  2.21487135, 29.7828834 ,  2.01658154,  0.88864766],
       [ 0.98868845,  0.94742019,  2.01658154, 52.01123953,  2.00083838],
       [ 2.09980341,  0.95599492,  0.88864766,  2.00083838, 26.48450165]])

In [11]:
b = service.get_channel_mean_variance()[1]
b1 = np.repeat(b[:, None], b.shape[0], axis=-1)
b2 = np.repeat(b[None, :], b.shape[0], axis=0)

In [21]:
np.round(a / (b1*b2), 3)

array([[2.1491e+01, 7.0800e-01, 4.1300e-01, 9.1800e-01, 2.3400e-01],
       [7.0800e-01, 1.5384e+01, 5.4100e-01, 5.1100e-01, 6.2000e-02],
       [4.1300e-01, 5.4100e-01, 9.4090e+00, 1.4070e+00, 7.4000e-02],
       [9.1800e-01, 5.1100e-01, 1.4070e+00, 8.0189e+01, 3.7000e-01],
       [2.3400e-01, 6.2000e-02, 7.4000e-02, 3.7000e-01, 5.8600e-01]])